import Head from 'next/head'
import Image from 'next/image'
import Box from '@mui/material/Box'
import styles from '../styles/Home.module.css'
import Header from '../component/Header'
import MovieSection from '../component/MovieSection'
import Popular from '../component/Jujutsu'


export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MovieSection />
      <Popular />
    </Box>

  )
}
